type: docker
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: clone
    image: "drone/git:latest"
    environment:
      HTTP_PROXY:
        from_secret: proxy
      HTTPS_PROXY:
        from_secret: proxy
      http_proxy:
        from_secret: proxy
      https_proxy:
        from_secret: proxy
      NOPROXY: localhost
      noproxy: localhost
  - name: build
    image: rancher/dapper:v0.5.8
    environment:
      PROXY:
        from_secret: proxy
      GOPROXY: https://goproxy.cn,direct
    commands:
      - dapper ci
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - push
        - pull_request
        - tag

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-amd64.txt
      checksum_flatten: true
      files:
        - "dist/artifacts/*"
    when:
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish-head
    image: plugins/docker
    settings:
      build_args:
        - ARCH=amd64
      custom_dns: 1.1.1.1
      dockerfile: package/Dockerfile
      tag: latest
      password:
        from_secret: docker_password
      repo: cnrancher/pdf-sender
      username:
        from_secret: docker_username
    when:
      ref:
        include:
          - "refs/heads/master"
      event:
        - push

  - name: docker-publish
    image: plugins/docker
    settings:
      build_args:
        - ARCH=amd64
      custom_dns: 1.1.1.1
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: cnrancher/pdf-sender
      tag: "${DRONE_TAG}"
      username:
        from_secret: docker_username
    when:
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  event:
    exclude:
      - promote
